name: lint_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff==0.11.2 pytest==8.3.5 pytest-html==4.1.1 requests

    - name: Install application dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 

    - name: Run linting
      run: make lint
      
    - name: Run tests
      run: make test
